=== MRI-Lab-Graz/bidspm/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "WD", "BIDS_DIR", "DERIVATIVES_DIR", "FMRIPREP_DIR", "SPACE", "FWHM", "MODELS_FILE", "TASKS"
  ],
  "properties": {
    "WD": {"type": "string"},
    "BIDS_DIR": {"type": "string"},
    "DERIVATIVES_DIR": {"type": "string"},
    "FMRIPREP_DIR": {"type": "string"},
    "SPACE": {"type": "string"},
    "FWHM": {"type": "number"},
    "MODELS_FILE": {"type": "string"},
    "TASKS": {
      "type": "array",
      "items": {"type": "string"},
      "minItems": 1
    },
    "VERBOSITY": {"type": "integer", "minimum": 0, "maximum": 3},
    "SUBJECTS": {
      "type": "array",
      "items": {"type": "string"}
    },
    "ROI": {"type": "boolean"},
    "ROI_CONFIG": {
      "type": "object",
      "properties": {
        "roi_atlas": {"type": "string"},
        "roi_name": {
          "type": "array",
          "items": {"type": "string"}
        },
        "space": {
          "type": "array",
          "items": {"type": "string"}
        }
      },
      "required": ["roi_atlas", "roi_name", "space"]
    }
  },
  "additionalProperties": false
}

=== MRI-Lab-Graz/bidspm/config/config_local_107.json
{
  "WD": "/data/local/107_JM01",
  "BIDS_DIR": "/data/local/107_JM01/rawdata",
  "DERIVATIVES_DIR": "/data/local/107_JM01/derivatives",
  "FMRIPREP_DIR": "/data/local/107_JM01/derivatives/fmriprep",
  "SPACE": "MNI152NLin2009cAsym",
  "FWHM": 8,
  "MODELS_FILE": "/data/local/107_JM01/code/old_models/latest_model.json",
  "TASKS": ["pa"],
  "VERBOSITY": 3
}

=== MRI-Lab-Graz/bidspm/config_107.json
{
  "WD": "/data/local/107_JM01",
  "BIDS_DIR": "/data/local/107_JM01/rawdata",
  "SPACE": "MNI152NLin2009cAsym",
  "FWHM": 8,
  "MODELS_FILE": "/data/local/107_JM01/code/old_models/models/model_pa_ses-2.json",
  "FMRIPREP_DIR": "/data/local/107_JM01/derivatives/fmriprep/",
  "DERIVATIVES_DIR": "/data/local/107_JM01/derivatives/",
  "TASKS": ["pa"],
 "VERBOSITY": 0
}

=== MRI-Lab-Graz/bidspm/config/config.example.json
{
  "WD": "/path/to/your/study",
  "BIDS_DIR": "/path/to/your/study/rawdata",
  "DERIVATIVES_DIR": "/path/to/your/study/derivatives",
  "FMRIPREP_DIR": "/path/to/your/study/derivatives/fmriprep",
  "SPACE": "MNI152NLin2009cAsym",
  "FWHM": 8,
  "MODELS_FILE": "/path/to/your/study/code/models/model.json",
  "TASKS": ["task_name"],
  "VERBOSITY": 3
}

=== MRI-Lab-Graz/bidspm/config.json
{
  "WD": "/Volumes/Thunder/138",
  "BIDS_DIR": "/Volumes/Thunder/138/rawdata",
  "DERIVATIVES_DIR": "/Volumes/Thunder/138/derivatives",
  "FMRIPREP_DIR": "/Volumes/Thunder/138/derivatives/bidspm-preproc",
  "SPACE": "MNI152NLin6Asym",
  "FWHM": 8,
  "MODELS_FILE": "model_d1c.json",
  "TASKS": ["symbol"],
  "ROI": false,
  "ROI_CONFIG": {
    "roi_atlas": "wang",
    "roi_name": ["V1v", "V1d"],
    "space": ["MNI152NLin6Asym"]
  }
}
